apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cluster: management
    component: vpn-server
  name: vpn-server-data
  namespace: __NPH_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi