kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: vpn
  name: vpn
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: vpn
  template:
    metadata:
      labels:
        cluster: management
        component: vpn
    spec:
      containers:
        - name: vpn
          image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/vpn:__NPH_VERSION
          imagePullPolicy: Always
          args:
            - "run"
            - "--debug"
            - "--vpnServerAddress=localhost"
            - "--port=5555"
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 443
              name: vpn-a
              protocol: TCP
            - containerPort: 5555
              name: vpn-b
              protocol: TCP